name: Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New Package Version (eg. 0.11.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm ci
    - run: npm version ${{ github.event.inputs.newVersion }}
    - run: npm run build
    - run: npm publish